### ISSUE TITLE
Game Hangs

### ISSUE THREAD

**Issue by GregoryLundberg** [GregoryLundberg/wesnoth#38]
THoT S06 playing to run out turns and see what happens. I was trying to run and hide and got cornered.

At this save, what I do is attack the closest, highest HP with my two units and End Turn. The game hangs at that point.
[THoT-Invaders-Auto-Save29.gz](https://github.com/GregoryLundberg/wesnoth/files/478477/THoT-Invaders-Auto-Save29.gz)

**Comment by jyrkive** [comment]
> 20160918 02:15:55< tad_> Let me restart and load it and I'll tell you which tile I hit with whom
> 20160918 02:17:18< tad_> Aiglondur (28,5) -> Binak (28,6) w/hammer
> 20160918 02:17:25< mattsc> Ooo, I just got it to crash on me with this:
> 20160918 02:17:27< mattsc> “Assertion failed: (row < rows_), function val, file /mats/misc/Wesnoth/wesnoth/src/attack_prediction.cpp, line 493."
> 20160918 02:18:07< tad_> Angarthing (29,5) --> Grol (28,4) w/bolas
> 20160918 02:18:17< tad_> End Turn

The hang is very likely related to the assertion failure.

> 20160918 02:23:29< tad_> And I disabled Monte Carlo, replayed my attacks and End Turn and *NO* hang

The hang (and very likely, the assertion) only occurs when Monte Carlo simulation is enabled. Thus, the bug is definitely my fault. I'll have a look next week.

The assertion fails when the HP of a combatant exceeds the maximum HP. It should be impossible: attacks can only ever reduce the HP (heck, the damage is represented with a unsigned integer!), and drain is clamped.

On top of that, I tested Monte Carlo simulation code in practice. I used the [built-in combat generator](https://github.com/wesnoth/wesnoth/blob/0e87d7fd436588f88fc093fd460b80903e1c5f4e/src/attack_prediction.cpp#L2124) to simulate thousands of fights, and allowed the AI to play a turn in a special build that uses Monte Carlo simulation for **all** combat simulation.

Thus, you must have hit some nasty corner case. Thank you for finding the bug - this is exactly the kind of bug that can only be found with real-world testing. We're lucky to have found the bug now and not, say, after the release of Wesnoth 1.14. :)

**Comment by GregoryLundberg** [comment]
Oh yeah, while I feel bad at times because I find so many bugs and pester people about them on IRC, it is good we're finding them on a dev branch and not after a major release.

I was just testing running out to turn 40 because I wondered what would happen with all those villages spawning. I started hanging back and only started running away once the Orcs were close. Unfortunately (for me .. good for finding the bug) I got cornered and was being swarmed.

Testing later, I killed ONE unit and determined:
(a) If the unit was in a fight (the Bandit in the NW corner) the hang did not occur
(b) If the unit was not (a solitary unit to the source) the hang still occurred.

So it's an edge condition which has to do with the total number of combats on the board.

Take your time. This is not a show-stopper for me. I've already moved on to bugs I can fix.

If, when testing, you get a Lua error in this scene, the fixes are in my GL_THoT branch. But I doubt you'll need them.

**Comment by jyrkive** [comment]
> So it's an edge condition which has to do with the total number of combats on the board.

That's very unlikely. Combat simulation code doesn't know anything about how many fights there are in total. Only AI has that information.

A more likely explanation is that the problematic fight isn't simulated (or is simulated with a different starting HP or something) if you kill random units. Chaos theory is at play here. It is very unpredictable how the AI internals react when you change things in the map. One change leads to another and eventually the AI doesn't simulate the problematic fight at all.

**Comment by jyrkive** [comment]
Should be fixed in https://github.com/wesnoth/wesnoth/commit/9f379b96e34236d087d1788add77698602dd78b9
